workflows:
  ios-workflow:
    name: Build and Test iOS App
    max_build_duration: 120
    platform:
      ios:
        flutter: true
        cocoapods: true
    build:
      ios:
        flutter: true
        cocoapods: true
    test:
      test_name: Run iOS Tests
      test_app: true
