workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - echo "Start building iOS app"
      - xcodebuild -workspace HelloWorld.xcworkspace -scheme HelloWorld -sdk iphoneos -configuration Release clean build
    artifacts:
      - build/ios/iphoneos/*.ipa
